### ISSUE TITLE
Please remove all references to Yr trademark

### ISSUE THREAD

**Issue by geira** [BleachDev/Rainy#1]
As per the MET API [TOS](https://api.met.no/doc/TermsOfService):

> You are not allowed to make services/sites that appear to be made by Yr, NRK or The Norwegian Meteorological Institute. In other words, you may not use the word "Yr" as a part of your service name, or attach the Yr logo to your service.

Please rename your app and remove the Yr logo from the code and website.

**Comment by BleachDev** [comment]
Done. Any plans for an official Garmin weather app?
