### ISSUE TITLE
Values does not match Yrno app even if sync is done 0 minutes ago.

### ISSUE THREAD

**Issue by frspp** [BleachDev/Rainy#4]
![image](https://github.com/BleachDev/Rainy/assets/22942340/6596f999-a176-47b9-be3d-8193648a4d7f)
![image](https://github.com/BleachDev/Rainy/assets/22942340/f128eff9-e7f4-4f09-b67f-cf547bbd19cb)
![image](https://github.com/BleachDev/Rainy/assets/22942340/cb90640c-c493-4184-a884-c4d4d01ba748)

**Comment by frspp** [comment]
I disabled bluetooth from phone some time ago and Rainy still says "updated 0 minutes ago".

Edit: And later also disabled phone connection from the watch and rainy still stays  "updated 0 minutes ago".

**Comment by BleachDev** [comment]
Seems like after the last update both the sync time and all the hourly forecasts gets wiped if you lose connection because it doesn't properly save the sync time. Which would also explain why the forecast is so weird, 40bf462 should fix it (maybe)

**Comment by frspp** [comment]
Yes with 1.7.1 now it shows sync time more than 0 minutes.

**Comment by frspp** [comment]
... But does not refresh the data.
