### ISSUE TITLE
Feature request: use ICON-D2 for central Europe

### ISSUE THREAD

**Issue by orcofthedarkness** [BleachDev/Rainy#7]
Hi there, 
first of all, i wanna say thank you for this marvel of a weather app. use it (pro version) on daily basis. Well done.

I think I read somewhere, that Rainy uses [ECMWF ](https://luckgrib.com/models/ecmwf/)for any other location than in the Nordics. Is this correct?
I am wondering, if it would be possible to use [ICON-D2](https://luckgrib.com/models/dwd_icon_d2/) for locations in central Europe.
[ECMWF ](https://luckgrib.com/models/ecmwf/)is using a 27.8km resolution whereas [ICON-D2](https://luckgrib.com/models/dwd_icon_d2/) uses a 2.2km resolution
The difference is tremendous - especially in the short term forecast (48hrs)

here is the link to the [--> ICON model descripton <--](https://www.dwd.de/SharedDocs/downloads/DE/modelldokumentationen/nwv/icon/icon_dbbeschr_aktuell.pdf?view=nasPublication&nn=495490)

As I am "commuting" quite frequently between Norway and Austria, this would be a well received and appreciated feature.

thank you

**Comment by BleachDev** [comment]
Rainy doesn't directly use any weather models, it uses data from the [Yr.no api](https://api.met.no/weatherapi) so you would almost have to contact them if you want it implemented.
From what I've read Yr does use ECMWF outside the Nordics so you're correct in that.

But getting all the data in the app from the same service makes processing it a lot easier (and accessing it is free),
so unfortunately i don't think I will be able to add data from other services.

**Comment by orcofthedarkness** [comment]
Thank you for your quick response.
Yep, that makes sense. Will contact Yr then - who knows...

Think this can be closed.
